name: "Create Post from Issue Form"

on:
  issues:
    types: [opened, edited]

jobs:
  create-post:
    runs-on: ubuntu-latest
    if: contains(join(github.event.issue.labels.*.name, ','), 'new-post')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create post file from Issue Form
        run: |
          # Capturamos el Issue body
          BODY="${{ github.event.issue.body }}"
          
          echo "=== Body debug ==="
          echo "$BODY"
          echo "=================="

          # Parseamos cada campo buscando la línea '### <Heading>' y leyendo la siguiente
          TITLE=$(echo "$BODY"    | grep -A1 '^### Title'      | tail -n1)
          DATE=$(echo "$BODY"     | grep -A1 '^### Date'       | tail -n1)
          VISIBLE=$(echo "$BODY"  | grep -A1 '^### Visible'    | tail -n1)
          QUOTE=$(echo "$BODY"    | grep -A1 '^### Quote'      | tail -n1)
          SLUG=$(echo "$BODY"     | grep -A1 '^### Slug'       | tail -n1)
          YOUTUBE=$(echo "$BODY"  | grep -A1 '^### YouTube ID' | tail -n1)

          echo "title:   $TITLE"
          echo "date:    $DATE"
          echo "visible: $VISIBLE"
          echo "quote:   $QUOTE"
          echo "slug:    $SLUG"
          echo "youtube: $YOUTUBE"

          # Creamos la carpeta si no existe
          mkdir -p posts
          
          # Creamos el archivo con el frontmatter e iframe
          cat <<EOF > "posts/${SLUG}.md"
---
title: $TITLE
date: $DATE
visible: $VISIBLE
quote: $QUOTE
slug: '$SLUG'
---
<iframe src="https://www.youtube.com/embed/$YOUTUBE" allowfullscreen></iframe>
EOF

          git add "posts/${SLUG}.md"
          git commit -m "Add post from Issue: $TITLE"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
