name: Create Post from Issue Form

on:
  issues:
    types: [opened, edited]

jobs:
  create-post:
    runs-on: ubuntu-latest

    if: contains(join(github.event.issue.labels.*.name, ','), 'new-post')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create post file from Issue Form
        run: |
          # Capture the Issue body
          BODY="${{ github.event.issue.body }}"

          # Show the body with invisible characters for debug
          echo "=== Body debug with cat -A ==="
          echo "$BODY" | cat -A
          echo "=============================="

          # Function: looks for the EXACT line "### <heading>", then prints the next line
          function get_value_after_heading() {
            local heading="^### $1$"
            echo "$BODY" \
              | sed 's/\r//g' \            # remove possible Windows \r
              | sed 's/[ \t]*$//g' \       # remove trailing spaces/tabs
              | awk -v heading="$heading" '
                  $0 ~ heading {
                    getline
                    gsub(/\r$/, "", $0)
                    print $0
                    exit
                  }
                '
          }

          # Extract each field by matching the lines in the Issue body
          TITLE=$(get_value_after_heading "Title")
          DATE=$(get_value_after_heading "Date")
          VISIBLE=$(get_value_after_heading "Visible")
          QUOTE=$(get_value_after_heading "Quote")
          SLUG=$(get_value_after_heading "Slug")
          YOUTUBE=$(get_value_after_heading "YouTube ID")

          echo "TITLE=$TITLE"
          echo "DATE=$DATE"
          echo "VISIBLE=$VISIBLE"
          echo "QUOTE=$QUOTE"
          echo "SLUG=$SLUG"
          echo "YOUTUBE=$YOUTUBE"

          # Generate a filename for the new post
          DATESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
          FILENAME="${DATESTAMP}-${SLUG}.md"

          # Ensure the 'posts' folder exists
          mkdir -p posts

          # Create the Markdown file with frontmatter and iframe
          {
            echo "---"
            echo "title: $TITLE"
            echo "date: $DATE"
            echo "visible: $VISIBLE"
            echo "quote: $QUOTE"
            echo "slug: '$SLUG'"
            echo "---"
            echo
            echo "<iframe src=\"https://www.youtube.com/embed/$YOUTUBE\" allowfullscreen></iframe>"
          } > "posts/$FILENAME"

          # Commit and push
          git add "posts/$FILENAME"
          git commit -m "Add post from Issue: $TITLE"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
