name: Crear Post desde Issue Form

on:
  issues:
    types: [opened, edited]

jobs:
  crear-post:
    runs-on: ubuntu-latest
    if: contains(join(github.event.issue.labels.*.name, ','), 'new-post')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Crear archivo a partir del Issue Form
        run: |
          BODY="${{ github.event.issue.body }}"

          function extract_field() {
            local field_id="$1"
            echo "$BODY" | awk "/<summary>$field_id<\\/summary>/{getline; print}" | sed 's/\r//g'
          }

          TITLE=$(extract_field "post_title")
          DATE=$(extract_field "post_date")
          VISIBLE=$(extract_field "post_visible")
          QUOTE=$(extract_field "post_quote")
          SLUG=$(extract_field "post_slug")
          YOUTUBE=$(extract_field "youtube_id")

          DATESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
          FILENAME="${DATESTAMP}-${SLUG}.md"

          mkdir -p posts

          echo "\---" > "posts/$FILENAME"
          echo "title: $TITLE" >> "posts/$FILENAME"
          echo "date: $DATE" >> "posts/$FILENAME"
          echo "visible: $VISIBLE" >> "posts/$FILENAME"
          echo "quote: $QUOTE" >> "posts/$FILENAME"
          echo "slug: '$SLUG'" >> "posts/$FILENAME"
          echo "\---" >> "posts/$FILENAME"
          echo "" >> "posts/$FILENAME"
          echo "<iframe src=\"https://www.youtube.com/embed/$YOUTUBE\" allowfullscreen></iframe>" >> "posts/$FILENAME"

          sed -i 's/\\---/---/g' "posts/$FILENAME"

          git add "posts/$FILENAME"
          git commit -m "Agregar post desde Issue: $TITLE"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
